#spring.application.name=demo
server.port=8080

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=hr
spring.datasource.password=hr

mybatis.type-aliases-package=com.example.myapp
mybatis.mapper-locations=classpath:mapper/**/*.xml

logging.level.com.example.myapp=info